//	Header generated by Constructor for Palm OS¨ 1.6
//
//	Generated at 9:14:37 AM on Saturday, February 23, 2002
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE FROM CONSTRUCTOR FOR PALM OS¨;
//	- DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"NSBSystemLib"
//
//	Palm App Version:		"2.0"

