	DC.W		libDispatchEntry(0)					// NSBLifeDriveLibOpen
	DC.W		libDispatchEntry(1)					// NSBLifeDriveLibClose
	DC.W		libDispatchEntry(2)					// NSBLifeDriveLibSleep
	DC.W		libDispatchEntry(3)					// NSBLifeDriveLibWake
	DC.W		libDispatchEntry(4)					// BrowserPresent
	DC.W		libDispatchEntry(5)					// BrowserOpenDialog
	DC.W		libDispatchEntry(6)					// BrowserSaveDialog
	DC.W		libDispatchEntry(7)					// PhotoPresent
	DC.W		libDispatchEntry(8)					// PhotoAlbumCount
	DC.W		libDispatchEntry(9)					// PhotoAlbumID
	DC.W		libDispatchEntry(10)					// PhotoAlbumName
	DC.W		libDispatchEntry(11)					// PhotoNewAlbum
	DC.W		libDispatchEntry(12)					// PhotoRenameAlbum
	DC.W		libDispatchEntry(13)					// PhotoDeleteAlbum
	DC.W		libDispatchEntry(14)					// PhotoDeleteAlbumAndContents
	DC.W		libDispatchEntry(15)					// PhotoImageCount
	DC.W		libDispatchEntry(16)					// PhotoSelectFromAlbum
	DC.W		libDispatchEntry(17)					// PhotoSelectImage
	DC.W		libDispatchEntry(18)					// PhotoSelectImages
	DC.W		libDispatchEntry(19)					// PhotoSelectVideo
	DC.W		libDispatchEntry(20)					// PhotoSelectVideos
	DC.W		libDispatchEntry(21)					// PhotoSelectNone
	DC.W		libDispatchEntry(22)					// PhotoSelectionCount
	DC.W		libDispatchEntry(23)					// PhotoSelectedImage
	DC.W		libDispatchEntry(24)					// PhotoDisplayImage
	DC.W		libDispatchEntry(25)					// PhotoImageName
