	DC.W		libDispatchEntry(0)					// NSBTreoLibOpen
	DC.W		libDispatchEntry(1)					// NSBTreoLibClose
	DC.W		libDispatchEntry(2)					// NSBTreoLibSleep
	DC.W		libDispatchEntry(3)					// NSBTreoLibWake
	DC.W		libDispatchEntry(4)					// PhoneOn
	DC.W		libDispatchEntry(5)					// SignalQuality
	DC.W		libDispatchEntry(6)					// PhoneType
	DC.W		libDispatchEntry(7)					// PhoneReady
	DC.W		libDispatchEntry(8)					// MainNumber
	DC.W		libDispatchEntry(9)					// NetworkAvailable
	DC.W		libDispatchEntry(10)					// CallWaiting
	DC.W		libDispatchEntry(11)					// CallWaitingSet
	DC.W		libDispatchEntry(12)					// OperatorCurName
	DC.W		libDispatchEntry(13)					// OperatorCurID
	DC.W		libDispatchEntry(14)					// Provider
	DC.W		libDispatchEntry(15)					// OperatorCount
	DC.W		libDispatchEntry(16)					// OperatorName
	DC.W		libDispatchEntry(17)					// Operator
	DC.W		libDispatchEntry(18)					// BookCount
	DC.W		libDispatchEntry(19)					// BookFirstName
	DC.W		libDispatchEntry(20)					// BookLastName
	DC.W		libDispatchEntry(21)					// BookPhoneNumber
	DC.W		libDispatchEntry(22)					// DialPhone
	DC.W		libDispatchEntry(23)					// SendSMSMessage
	DC.W		libDispatchEntry(24)					// SendEMail
	DC.W		libDispatchEntry(25)					// Browse
	DC.W		libDispatchEntry(26)					// BookReload
	DC.W		libDispatchEntry(27)					// PhoneTurnOn
	DC.W		libDispatchEntry(28)					// TCPIPDropConnection
	DC.W		libDispatchEntry(29)					// Vibrate
	DC.W		libDispatchEntry(30)					// Blink
	DC.W		libDispatchEntry(31)					// Roaming
	DC.W		libDispatchEntry(32)					// Software
	DC.W		libDispatchEntry(33)					// Hardware
	DC.W		libDispatchEntry(34)					// ProductName
	DC.W		libDispatchEntry(35)					// SerialNumber
	DC.W		libDispatchEntry(36)					// CarrierID
	DC.W		libDispatchEntry(37)					// ProductRevision
	DC.W		libDispatchEntry(38)					// ROM
	DC.W		libDispatchEntry(39)					// Firmware
	DC.W		libDispatchEntry(40)					// HTTPOpen
	DC.W		libDispatchEntry(41)					// HTTPClose
	DC.W		libDispatchEntry(42)					// HTTPSendRequest
	DC.W		libDispatchEntry(43)					// KeyboardLocked
	DC.W		libDispatchEntry(44)					// KeyboardLock
	DC.W		libDispatchEntry(45)					// HTTPGetHeader
	DC.W		libDispatchEntry(46)					// HTTPRead
	DC.W		libDispatchEntry(47)					// HTTPSendPostRequest
	DC.W		libDispatchEntry(48)					// HTTPEnd
	DC.W		libDispatchEntry(49)					// GetRingProfile
	DC.W		libDispatchEntry(50)					// SetRingProfile
	DC.W		libDispatchEntry(51)					// GetRoamWarnings
	DC.W		libDispatchEntry(52)					// SetRoamWarnings
	DC.W		libDispatchEntry(53)					// PhonePower
	DC.W		libDispatchEntry(54)					// GetLibRefNum
	DC.W		libDispatchEntry(55)					// GetRoamMode
	DC.W		libDispatchEntry(56)					// SetRoamMode
