//	Header generated by Constructor for Palm OS (R) 1.8
//
//	Generated at 10:53:41 AM on Thursday, April 10, 2003
//
//	Generated for file: E:\NSBP 3\nsb\Runtime\Src\Resource.frk\nsbasic.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE
//	DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"NSBRuntime"
//
//	Palm App Version:		"3.0.3 Beta 3"


//	Resource: PICT 1000
#define BitmapID1000Bitmap                        1000


//	Resource: taif 1000
#define LargeAppIconAppIconFamily                 1000

