	DC.W		libDispatchEntry(0)					// NSB_SSMLibOpen
	DC.W		libDispatchEntry(1)					// NSB_SSMLibClose
	DC.W		libDispatchEntry(2)					// NSB_SSMLibSleep
	DC.W		libDispatchEntry(3)					// NSB_SSMLibWake
	DC.W		libDispatchEntry(4)					// NSB_SSMLibIsPalmSymbolUnit
	DC.W		libDispatchEntry(5)					// NSB_SSMLibCmdScanEnable
	DC.W		libDispatchEntry(6)					// NSB_SSMLibCmdScanDisable
	DC.W		libDispatchEntry(7)					// NSB_SSMLibCmdScanSetTriggeringModes
	DC.W		libDispatchEntry(8)					// NSB_SSMLibCmdScanSetBarcodeEnabled
	DC.W		libDispatchEntry(9)					// NSB_SSMLibCmdSendParams
	DC.W		libDispatchEntry(10)					// NSB_SSMLibCmdStartDecode
	DC.W		libDispatchEntry(11)					// NSB_SSMLibCmdStopDecode
	DC.W		libDispatchEntry(12)					// NSB_SSMLibGetDecodedData
	DC.W		libDispatchEntry(13)					// NSB_SSMLibGetLastScanData
	DC.W		libDispatchEntry(14)					// NSB_SSMLibGetBarType
	DC.W		libDispatchEntry(15)					// NSB_SSMLibCmdScanLedOn
	DC.W		libDispatchEntry(16)					// NSB_SSMLibCmdScanLedOff
